"""
grammar.py
----------
Stage 2.5: Grammar-constrained generation for SVA assertions.

Generates a GBNF grammar that constrains LLM output so that:
- Signal identifiers must come from ``RTLFacts.all_signals``
- SVA syntax follows common assertion patterns
- Verilog literals, operators, comments, and error messages are free-form

The grammar is intentionally permissive for everything EXCEPT signal names.
This prevents hallucinated signals while allowing the LLM creative freedom
for assertion structure, temporal operators, and error messages.

Supported backends:
- vLLM:  ``extra_body={"guided_grammar": gbnf_string}``
- SGLang: similar to vLLM
- Local HF (outlines): ``outlines.generate.cfg(model, gbnf_string)``
- Ollama: NOT supported via OpenAI API (requires raw /api/generate)

Gate: ``config.use_grammar_constraints`` (default False).
"""

import logging
import re
from typing import Optional, Set

logger = logging.getLogger(__name__)

# SystemVerilog keywords that are valid identifiers in assertion context.
# These are added to the signal allowlist in the grammar so the LLM can
# use standard SV constructs without being blocked.
_SV_ASSERTION_KEYWORDS = {
    # Assertion keywords
    "assert", "property", "sequence", "cover", "assume",
    "else", "iff", "disable",
    # Edge / timing
    "posedge", "negedge",
    # Operators that look like identifiers
    "or", "and", "not",
    # System functions the LLM commonly uses
    # (prefixed with $ in SV, but the grammar handles $ separately)
    # Type keywords that may appear in expressions
    "signed", "unsigned",
}

# Common SV system functions (after $) that should be allowed.
_SV_SYSTEM_FUNCTIONS = {
    "error", "warning", "info", "fatal",
    "bits", "past", "rose", "fell", "stable", "changed",
    "countones", "onehot", "onehot0", "isunknown",
    "clog2", "display",
}


def _escape_gbnf_string(s: str) -> str:
    """Escape a string for use in a GBNF quoted terminal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _build_signal_alternatives(signals: Set[str]) -> str:
    """
    Build a GBNF alternation rule for the signal allowlist.

    Each signal becomes a quoted terminal: ``"out_data" | "in_code" | ...``
    Signals are sorted for deterministic output and easier debugging.

    For large designs (500+ signals), this produces a long rule but GBNF
    parsers handle it efficiently (it's just a trie match).
    """
    if not signals:
        return '"_unknown_"'

    # Sort by length descending so longer names match first (greedy).
    sorted_sigs = sorted(signals, key=lambda s: (-len(s), s))
    return " | ".join(f'"{_escape_gbnf_string(s)}"' for s in sorted_sigs)


def generate_sva_grammar(
    all_signals: Set[str],
    *,
    clock_signals: Optional[Set[str]] = None,
    reset_signals: Optional[Set[str]] = None,
) -> str:
    """
    Generate a GBNF grammar for SVA assertion output.

    The grammar constrains signal identifiers to the allowlist while
    keeping everything else (operators, literals, strings, comments)
    free-form. It covers the two main assertion patterns the pipeline
    produces:

    1. Immediate: ``assert (cond) else $error("msg");``
    2. Concurrent: ``assert property (@(posedge clk) disable iff (!rst)
       cond |-> consequence) else $error("msg");``

    Plus comments (``// ...``) and blank lines between assertions.

    Parameters
    ----------
    all_signals : set of str
        Every valid signal name (from ``RTLFacts.all_signals``).
    clock_signals : set of str, optional
        Clock signal names (for the ``@(posedge ...)`` rule).
    reset_signals : set of str, optional
        Reset signal names (for the ``disable iff`` rule).

    Returns
    -------
    str
        A complete GBNF grammar string ready to pass to vLLM or outlines.
    """
    # Merge SV keywords into the identifier allowlist.
    allowed_ids = set(all_signals) | _SV_ASSERTION_KEYWORDS
    signal_alts = _build_signal_alternatives(all_signals)
    id_alts = _build_signal_alternatives(allowed_ids)

    # Clock and reset alternatives (subset for structural rules).
    clk_alts = _build_signal_alternatives(
        clock_signals if clock_signals else all_signals
    )
    rst_alts = _build_signal_alternatives(
        reset_signals if reset_signals else all_signals
    )

    # System function alternatives.
    sysfn_alts = " | ".join(
        f'"{f}"' for f in sorted(_SV_SYSTEM_FUNCTIONS)
    )

    grammar = f"""\
# GBNF grammar for SVA assertions with signal-name allowlist.
# Auto-generated by sva_pipeline.grammar — do not edit manually.
#
# Constraints:
# - Identifiers in expressions must be from the RTL signal list
# - SVA syntax follows common immediate/concurrent patterns
# - Comments, literals, and error messages are free-form

root ::= (assertion-block | comment-line | blank-line)* fence-close?

# -- Top-level assertion patterns --

assertion-block ::= comment-line? assertion-line ws

assertion-line ::= immediate-assertion | concurrent-assertion

immediate-assertion ::= "assert" ws "(" ws expr ws ")" ws error-clause? ";" ws

concurrent-assertion ::= "assert" ws "property" ws "(" ws property-body ws ")" ws error-clause? ";" ws

# -- Property body (concurrent assertions) --

property-body ::= clock-event ws disable-clause? temporal-expr

clock-event ::= "@(" ws edge ws signal ws ")"

edge ::= "posedge" | "negedge"

disable-clause ::= "disable" ws "iff" ws "(" ws expr ws ")" ws

temporal-expr ::= expr (ws temporal-op ws expr)?

temporal-op ::= "|->" | "|=>"

# -- Expressions --

expr ::= unary-expr (ws binop ws unary-expr)*

unary-expr ::= "!" ws? unary-expr
             | "~" ws? unary-expr
             | primary

primary ::= "(" ws expr ws ")"
          | concat
          | sysfn-call
          | signal-ref
          | literal

concat ::= "{{" ws expr-list ws "}}"

expr-list ::= expr (ws "," ws expr)*

signal-ref ::= signal bit-select?

bit-select ::= "[" ws bit-range ws "]"

bit-range ::= [0-9]+ (ws ":" ws [0-9]+)?

signal ::= {signal_alts}

# -- Operators --

binop ::= "==" | "!=" | "&&" | "||" | "&" | "|" | "^"
        | ">=" | "<=" | ">" | "<" | "+" | "-" | "*"

# -- Literals --

literal ::= verilog-literal | decimal-literal

verilog-literal ::= [0-9]+ "'" [bBhHdDoO] [0-9a-fA-F_xXzZ]+

decimal-literal ::= [0-9]+

# -- System function calls --

sysfn-call ::= "$" sysfn-name "(" ws expr-list? ws ")"

sysfn-name ::= {sysfn_alts}

# -- Error clause --

error-clause ::= "else" ws "$error(" ws string ws ")"

string ::= "\\"" [^\\"]* "\\""

# -- Comments and whitespace --

comment-line ::= ws "//" [^\\n]* "\\n"

blank-line ::= ws "\\n"

ws ::= [ \\t\\n]*

# -- Code fence (LLM may wrap output in markdown fences) --

fence-close ::= "```" ws
"""

    return grammar


def generate_sva_grammar_from_facts(facts) -> str:
    """
    Convenience wrapper: generate grammar directly from an RTLFacts instance.

    Parameters
    ----------
    facts : RTLFacts
        Pre-extracted RTL facts.

    Returns
    -------
    str
        GBNF grammar string. Empty string if facts have no signals.
    """
    if not facts.all_signals:
        return ""

    return generate_sva_grammar(
        all_signals=facts.all_signals,
        clock_signals=facts.clock_signals or None,
        reset_signals=facts.reset_signals or None,
    )
