#!/usr/bin/env python3
"""
token_cost_matrix.py
--------------------
Collate token_summary.json files into a single comparison table.

Walks a results directory, finds every <tag>_token_summary.json
emitted by main.py, pairs ``<design>_ours`` with ``<design>_naive``,
and produces:

  - summary.csv  : one row per run (machine readable)
  - summary.md   : per-pair comparison + aggregate table (human readable)

Token totals are reported regardless of whether assertions survived
the pipeline, so cost data is preserved even for runs that produced
zero output.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional


def find_summaries(results_dir: Path) -> Dict[str, dict]:
    """
    Walk results_dir for files matching ``<tag>.log`` and locate the
    token_summary.json each run wrote (it lives next to the SVA output
    file, not in the results dir). The mapping is keyed by tag.

    The tag convention is "<design>_<variant>" e.g. "cacc_ours" or
    "booth_naive". The token_summary path is read from the run log if
    present; otherwise we glob the workspace for the right filename.
    """
    workspace = Path.cwd()
    summaries: Dict[str, dict] = {}

    for log_path in sorted(results_dir.glob("*.log")):
        tag = log_path.stem
        if tag == "batch":
            continue

        # Try to extract the summary path from the log (it's printed
        # at the end). Fall back to a glob if that fails.
        summary_path: Optional[Path] = None
        try:
            with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    if "token_summary.json" in line:
                        # Format: "... Summary: <path>"
                        candidate = line.rstrip().rsplit(":", 1)[-1].strip()
                        # Strip trailing punctuation
                        candidate = candidate.rstrip(".,")
                        p = (workspace / candidate).resolve()
                        if p.exists():
                            summary_path = p
                            break
        except OSError:
            continue

        if summary_path is None:
            continue

        try:
            with open(summary_path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError):
            continue

        data["_tag"] = tag
        data["_summary_path"] = str(summary_path)
        summaries[tag] = data

    return summaries


def split_tag(tag: str) -> tuple[str, str]:
    """Split 'cacc_ours' -> ('cacc', 'ours')."""
    if "_" in tag:
        design, _, variant = tag.rpartition("_")
        return design, variant
    return tag, ""


def write_csv(out_path: Path, summaries: Dict[str, dict]) -> None:
    fields = [
        "tag", "design", "variant", "config",
        "naive_baseline", "llm_calls",
        "prompt_tokens", "completion_tokens", "total_tokens",
        "final_assertions", "tokens_per_assertion",
    ]
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(fields)
        for tag in sorted(summaries):
            s = summaries[tag]
            design, variant = split_tag(tag)
            w.writerow([
                tag, design, variant,
                s.get("config", ""),
                s.get("naive_baseline", False),
                s.get("llm_calls", 0),
                s.get("prompt_tokens", 0),
                s.get("completion_tokens", 0),
                s.get("total_tokens", 0),
                s.get("final_assertions", 0),
                s.get("tokens_per_assertion") or "",
            ])


def fmt_int(n: int) -> str:
    return f"{n:,}"


def fmt_pct(num: float, denom: float) -> str:
    if denom == 0:
        return "n/a"
    pct = (1.0 - num / denom) * 100.0
    return f"{pct:+.1f}%"


def write_markdown(out_path: Path, summaries: Dict[str, dict]) -> None:
    """
    Produce per-design comparison tables (ours vs naive) plus an
    aggregate row across all designs.
    """
    designs: Dict[str, Dict[str, dict]] = {}
    for tag, s in summaries.items():
        design, variant = split_tag(tag)
        designs.setdefault(design, {})[variant] = s

    lines: List[str] = []
    lines.append("# Token Cost Matrix\n")
    lines.append("Generated by `scripts/token_cost_matrix.py`. Token totals\n"
                 "are reported regardless of whether assertions survived\n"
                 "the pipeline.\n")

    agg_naive_tokens = 0
    agg_ours_tokens = 0
    agg_naive_assertions = 0
    agg_ours_assertions = 0

    for design in sorted(designs):
        variants = designs[design]
        ours = variants.get("ours")
        naive = variants.get("naive")

        lines.append(f"\n## {design}\n")

        if not ours and not naive:
            for v, s in sorted(variants.items()):
                lines.append(f"- **{v}**: {fmt_int(s.get('total_tokens', 0))} "
                             f"tokens, {s.get('final_assertions', 0)} assertions")
            continue

        lines.append("| Metric | Naive baseline | Our pipeline | Reduction |")
        lines.append("|---|---:|---:|---:|")

        def col(s: Optional[dict], key: str, default=0) -> int:
            return int(s.get(key, default)) if s else 0

        n_calls = col(naive, "llm_calls")
        o_calls = col(ours, "llm_calls")
        n_pt = col(naive, "prompt_tokens")
        o_pt = col(ours, "prompt_tokens")
        n_ct = col(naive, "completion_tokens")
        o_ct = col(ours, "completion_tokens")
        n_tt = col(naive, "total_tokens")
        o_tt = col(ours, "total_tokens")
        n_as = col(naive, "final_assertions")
        o_as = col(ours, "final_assertions")

        lines.append(f"| LLM calls | {fmt_int(n_calls)} | {fmt_int(o_calls)} | "
                     f"{fmt_pct(o_calls, n_calls)} |")
        lines.append(f"| Prompt tokens | {fmt_int(n_pt)} | {fmt_int(o_pt)} | "
                     f"{fmt_pct(o_pt, n_pt)} |")
        lines.append(f"| Completion tokens | {fmt_int(n_ct)} | {fmt_int(o_ct)} | "
                     f"{fmt_pct(o_ct, n_ct)} |")
        lines.append(f"| **Total tokens** | **{fmt_int(n_tt)}** | "
                     f"**{fmt_int(o_tt)}** | **{fmt_pct(o_tt, n_tt)}** |")
        lines.append(f"| Final assertions | {fmt_int(n_as)} | {fmt_int(o_as)} | — |")

        if n_as > 0 and o_as > 0:
            n_tpa = n_tt / n_as
            o_tpa = o_tt / o_as
            lines.append(f"| **Tokens / assertion** | **{n_tpa:,.0f}** | "
                         f"**{o_tpa:,.0f}** | **{fmt_pct(o_tpa, n_tpa)}** |")
        elif o_as > 0:
            o_tpa = o_tt / o_as
            lines.append(f"| Tokens / assertion | n/a (0 assertions) | "
                         f"{o_tpa:,.0f} | n/a |")
        else:
            lines.append("| Tokens / assertion | n/a | n/a | n/a |")

        agg_naive_tokens += n_tt
        agg_ours_tokens += o_tt
        agg_naive_assertions += n_as
        agg_ours_assertions += o_as

    # Aggregate
    lines.append("\n## Aggregate (all designs)\n")
    lines.append("| Metric | Naive baseline | Our pipeline | Reduction |")
    lines.append("|---|---:|---:|---:|")
    lines.append(f"| Total tokens | {fmt_int(agg_naive_tokens)} | "
                 f"{fmt_int(agg_ours_tokens)} | "
                 f"{fmt_pct(agg_ours_tokens, agg_naive_tokens)} |")
    lines.append(f"| Total assertions | {fmt_int(agg_naive_assertions)} | "
                 f"{fmt_int(agg_ours_assertions)} | — |")
    if agg_naive_assertions > 0 and agg_ours_assertions > 0:
        n_tpa = agg_naive_tokens / agg_naive_assertions
        o_tpa = agg_ours_tokens / agg_ours_assertions
        lines.append(f"| **Tokens / assertion** | **{n_tpa:,.0f}** | "
                     f"**{o_tpa:,.0f}** | **{fmt_pct(o_tpa, n_tpa)}** |")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--results-dir", required=True, type=Path,
                   help="Directory with batch *.log files")
    p.add_argument("--output", type=Path, default=None,
                   help="CSV output path (default: <results-dir>/summary.csv)")
    p.add_argument("--markdown", type=Path, default=None,
                   help="Markdown output path (default: <results-dir>/summary.md)")
    args = p.parse_args()

    results_dir = args.results_dir.resolve()
    if not results_dir.is_dir():
        print(f"error: {results_dir} is not a directory", file=sys.stderr)
        return 1

    csv_out = args.output or (results_dir / "summary.csv")
    md_out = args.markdown or (results_dir / "summary.md")

    summaries = find_summaries(results_dir)
    if not summaries:
        print(f"warning: no token_summary.json files found via {results_dir}",
              file=sys.stderr)
        return 0

    write_csv(csv_out, summaries)
    write_markdown(md_out, summaries)

    print(f"Found {len(summaries)} run(s).")
    print(f"  CSV : {csv_out}")
    print(f"  MD  : {md_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
